-- 用户表
CREATE TABLE IF NOT EXISTS `T_USER`(
    `USER_ID` VARCHAR(255)  NOT NULL COMMENT '用户id',
    `USER_NAME` VARCHAR(255) NOT NULL COMMENT '用户名字',
    `PASSWORD`  VARCHAR(2048) NOT NULL COMMENT '用户密码',
    `ROLE_ID` INT(11) NOT NULL COMMENT '角色id',
    `CREATE_TIME` BIGINT(255) NOT NULL COMMENT '创建时间',
    `MODIFY_TIME` BIGINT(255)  NOT NULL COMMENT '密码修改时间',
    `DESCRIPTION` VARCHAR(2048) DEFAULT "" COMMENT '描述信息',
     PRIMARY KEY (`USER_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;


-- 角色表
CREATE TABLE IF NOT EXISTS `T_ROLE`(
    `ROLE_ID` INT(11) NOT NULL ,
    `ROLE_NAME` VARCHAR(255) NOT NULL,
     primary key (`ROLE_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
-- 用户角色表
CREATE TABLE IF NOT EXISTS `T_USER_R_ROLE`(
    `USER_ID`  VARCHAR(255) NOT NULL,
    `ROLE_ID`  INT(11) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

-- init default role

INSERT INTO  `system_base`.`t_role`(`ROLE_ID`,`ROLE_NAME`) VALUES ('1','ADMIN_ROLE');
INSERT INTO  `system_base`.`t_role`(`ROLE_ID`,`ROLE_NAME`) VALUES ('2','SHENJI_ROLE');